name: Update Lando WinGet Package

on:
  workflow_dispatch:

jobs:
  update:
    name: Update Lando Package
    runs-on: ubuntu-latest
    
    steps:
    - name: Update Lando Package
      uses: michidk/run-komac@latest
      with:
        komac-version: "2.6.0"
        args: update Lando.Lando --token=${{ secrets.GITHUB_TOKEN }} --version=${{ env.VERSION }} --urls=https://github.com/lando/core/releases/download/v{VERSION}/lando-win-x64-v{VERSION}-slim.exe --urls=https://github.com/lando/core/releases/download/v{VERSION}/lando-win-arm64-v{VERSION}-slim.exe

  cleanup:
    name: Cleanup branches
    needs: update
    runs-on: ubuntu-latest

    steps:
    - name: Run Komac
      uses: michidk/run-komac@latest
      with:
        args: 'cleanup --only-merged --token=${{ secrets.GITHUB_TOKEN }}'